Repository netlify/edge-functions-examples, pull requests merged in 2022-08, with the labels that each got.

#29 fix: replace netlify:edge identifier with full URL
  netlify/edge-functions/abtest.ts
  netlify/edge-functions/context-site.ts
  pages/context-site/README.md
  pages/context-site/index.js
Labels: type: bug

#31 showcasing webassembly
  netlify.toml
  netlify/edge-functions/[page].js
  netlify/edge-functions/wasm.ts
  pages/home/index.js
  pages/wasm/README.md
  pages/wasm/index.js
Labels: type: feature

#32 fix(#30): Updates localized-content with fallback
  netlify/edge-functions/localized-content.js
Labels: type: bug

#33 update docs link
  components/layout.js
Labels: type: chore
